# Generated by Django 5.2.14 on 2026-05-11 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryPurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("supplier", models.CharField(db_index=True, max_length=180)),
                ("items", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(db_index=True, default="draft", max_length=40),
                ),
                (
                    "expected_delivery",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "received_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["expected_delivery", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "expected_delivery"],
                        name="inventory_i_status_0bc5b2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sku", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(db_index=True, max_length=180)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reorder_level",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("lead_time_days", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["sku"],
                "indexes": [
                    models.Index(
                        fields=["category", "name"],
                        name="inventory_p_categor_4cd409_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("movement_type", models.CharField(db_index=True, max_length=40)),
                ("quantity", models.IntegerField()),
                (
                    "reference_doc",
                    models.CharField(blank=True, db_index=True, max_length=140),
                ),
                ("warehouse", models.CharField(db_index=True, max_length=120)),
                ("moved_at", models.DateTimeField(db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-moved_at"],
            },
        ),
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("warehouse", models.CharField(db_index=True, max_length=120)),
                ("quantity", models.IntegerField(default=0)),
                ("reserved_qty", models.IntegerField(default=0)),
                ("available_qty", models.IntegerField(db_index=True, default=0)),
                ("last_updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["warehouse", "product__sku"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "warehouse"),
                        name="unique_product_warehouse_stock",
                    )
                ],
            },
        ),
    ]
