# Generated by Django 4.2.16 on 2026-05-08 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="connection_status",
            field=models.CharField(
                choices=[
                    ("DISCONNECTED", "Disconnected"),
                    ("CONNECTED", "Connected"),
                    ("SYNCING", "Syncing"),
                    ("DEPLOYING", "Deploying"),
                    ("ERROR", "Error"),
                ],
                default="DISCONNECTED",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="connection_status_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="connection_type",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("LOCAL", "Local"),
                    ("HOSTED", "Hosted"),
                    ("GITHUB", "GitHub"),
                ],
                default="NONE",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="github_default_branch",
            field=models.CharField(blank=True, default="main", max_length=120),
        ),
        migrations.AddField(
            model_name="project",
            name="github_owner",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="project",
            name="github_repo",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="project",
            name="hosted_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="last_commit_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="last_commit_author",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="project",
            name="last_commit_message",
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name="project",
            name="last_commit_sha",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="project",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="local_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="selected_branch",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="ProjectCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sha", models.CharField(max_length=80)),
                ("branch", models.CharField(blank=True, max_length=120)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("author_name", models.CharField(blank=True, max_length=180)),
                ("author_email", models.EmailField(blank=True, max_length=254)),
                ("author_login", models.CharField(blank=True, max_length=120)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("html_url", models.URLField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-committed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "branch", "committed_at"],
                        name="projects_pr_project_237bcf_idx",
                    ),
                    models.Index(
                        fields=["author_email"], name="projects_pr_author__28d57c_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="projectcommit",
            constraint=models.UniqueConstraint(
                fields=("project", "sha", "branch"), name="unique_project_commit_branch"
            ),
        ),
    ]
