# Generated by Django 4.2.16 on 2026-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_connection_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="features_to_implement",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="local_repository_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="project",
            name="project_idea",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies_used",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="workflow_days",
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
