# Generated by Django 4.2.16 on 2026-05-08 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0003_project_features_to_implement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="approval_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("IN_REVIEW", "In review"),
                    ("APPROVED", "Approved"),
                    ("CORRECTION_REQUESTED", "Correction requested"),
                ],
                default="DRAFT",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="accounts.team"
            ),
        ),
    ]
