# Generated by Django 4.2.16 on 2026-05-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("enterprise", "__first__"),
        ("projects", "0004_project_approval_note_project_approval_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="enterprise.company",
            ),
        ),
    ]
