# Generated by Django 5.2.14 on 2026-05-11 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
        ("hr", "0001_initial"),
        ("projects", "0006_project_project_flow_project_flow_generated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="UCEProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(db_index=True, max_length=180)),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=40),
                ),
                (
                    "budget",
                    models.DecimalField(
                        db_index=True, decimal_places=2, default=0, max_digits=14
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        db_index=True, decimal_places=2, default=0, max_digits=14
                    ),
                ),
                ("start_date", models.DateField(blank=True, db_index=True, null=True)),
                ("deadline", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "progress",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uce_projects",
                        to="crm.company",
                    ),
                ),
            ],
            options={
                "db_table": "uce_project",
                "ordering": ["deadline", "name"],
            },
        ),
        migrations.CreateModel(
            name="UCEMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("title", models.CharField(db_index=True, max_length=180)),
                ("due_date", models.DateField(db_index=True)),
                ("completed", models.BooleanField(db_index=True, default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.uceproject",
                    ),
                ),
            ],
            options={
                "db_table": "uce_milestone",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="UCETask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("title", models.CharField(db_index=True, max_length=180)),
                (
                    "status",
                    models.CharField(db_index=True, default="todo", max_length=40),
                ),
                (
                    "priority",
                    models.CharField(db_index=True, default="medium", max_length=40),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "actual_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_tasks",
                        to="hr.employee",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="projects.ucemilestone",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uce_tasks",
                        to="projects.uceproject",
                    ),
                ),
            ],
            options={
                "db_table": "uce_task",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="UCETimeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("hours", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateField(db_index=True)),
                ("billable", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="hr.employee",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="projects.ucetask",
                    ),
                ),
            ],
            options={
                "db_table": "uce_time_entry",
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="uceproject",
            index=models.Index(
                fields=["status", "deadline"], name="uce_project_status_7aa578_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uceproject",
            index=models.Index(
                fields=["budget", "actual_cost"], name="uce_project_budget_9e3ec7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ucetask",
            index=models.Index(
                fields=["status", "priority"], name="uce_task_status_47a458_idx"
            ),
        ),
    ]
