# Generated by Django 4.2.16 on 2026-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("INFO", "Info"),
                    ("TASK", "Task"),
                    ("DEPLOYMENT", "Deployment"),
                    ("FILE", "File"),
                    ("ALERT", "Alert"),
                    ("WARNING", "Warning"),
                    ("SUCCESS", "Success"),
                ],
                default="INFO",
                max_length=32,
            ),
        ),
    ]
