# Generated by Django 4.2.16 on 2026-05-12 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hosting", "0001_initial"),
        ("server_monitor", "0001_initial"),
        ("notifications", "0002_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="hosted_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="hosting.hostedproject",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_sent_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="server_monitor.server",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="urgency",
            field=models.CharField(db_index=True, default="info", max_length=16),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(default="INFO", max_length=32),
        ),
    ]
