# Generated by Django 5.2.14 on 2026-05-20 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hosting", "0007_project_upload_deployment"),
        ("notifications", "0004_notification_days_threshold"),
        ("projects", "0007_uceproject_ucemilestone_ucetask_ucetimeentry_and_more"),
        ("server_monitor", "0001_initial"),
        ("tasks", "0005_backfill_task_progress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("expiry_warning", "Expiry warning"),
                    ("server_alert", "Server alert"),
                    ("disk_alert", "Disk alert"),
                    ("api_abuse", "API abuse"),
                    ("maintenance", "Maintenance"),
                    ("manual", "Manual"),
                    ("INFO", "Info"),
                    ("TASK", "Task"),
                    ("DEPLOYMENT", "Deployment"),
                    ("FILE", "File"),
                    ("ALERT", "Alert"),
                    ("WARNING", "Warning"),
                    ("SUCCESS", "Success"),
                ],
                default="INFO",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("critical", "Critical"),
                ],
                db_index=True,
                default="info",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["type", "urgency", "-created_at"],
                name="notificatio_type_36b55b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["hosted_project", "days_threshold", "-created_at"],
                name="notificatio_hosted__9812b7_idx",
            ),
        ),
    ]
