# Generated by Django 5.2.14 on 2026-05-11 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_id", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("schema", models.JSONField(default=dict)),
                ("capabilities", models.JSONField(default=dict)),
                ("endpoints", models.JSONField(default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                (
                    "health_status",
                    models.CharField(db_index=True, default="unknown", max_length=30),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["module_id"],
                "indexes": [
                    models.Index(
                        fields=["module_id", "is_active"],
                        name="core_module_module__a3d71b_idx",
                    ),
                    models.Index(
                        fields=["health_status"], name="core_module_health__4c22b8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UniversalQuery",
            fields=[
                (
                    "query_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_input", models.TextField()),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("sql", "SQL"),
                            ("rest", "REST"),
                            ("nl", "Natural Language"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("normalized_iql", models.JSONField(default=dict)),
                ("target_modules", models.JSONField(default=list)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_ms", models.IntegerField(blank=True, null=True)),
                ("result_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["query_type", "created_at"],
                        name="core_univer_query_t_681210_idx",
                    ),
                    models.Index(
                        fields=["created_by", "created_at"],
                        name="core_univer_created_948612_idx",
                    ),
                ],
            },
        ),
    ]
