# Generated by Django 5.2.14 on 2026-05-11 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=160, unique=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("large_transfer", "Large Transfer"),
                            ("sensitive_extension", "Sensitive Extension"),
                            ("off_hours", "Off Hours"),
                            ("disk_pressure", "Disk Pressure"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("threshold_bytes", models.BigIntegerField(default=1073741824)),
                ("extensions", models.JSONField(blank=True, default=list)),
                (
                    "severity",
                    models.CharField(db_index=True, default="medium", max_length=20),
                ),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DiskVolume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("label", models.CharField(db_index=True, max_length=120)),
                ("mount_path", models.CharField(max_length=500, unique=True)),
                (
                    "disk_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("usb", "USB"),
                            ("network", "Network"),
                            ("cloud", "Cloud"),
                        ],
                        db_index=True,
                        default="local",
                        max_length=30,
                    ),
                ),
                ("total_bytes", models.BigIntegerField(default=0)),
                ("used_bytes", models.BigIntegerField(db_index=True, default=0)),
                ("free_bytes", models.BigIntegerField(db_index=True, default=0)),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_online", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["label"],
                "indexes": [
                    models.Index(
                        fields=["disk_type", "is_online"],
                        name="file_tracki_disk_ty_80884f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FileTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("file_name", models.CharField(db_index=True, max_length=255)),
                (
                    "file_extension",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "mime_type",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "checksum",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("size_bytes", models.BigIntegerField(db_index=True, default=0)),
                ("source_path", models.CharField(db_index=True, max_length=1000)),
                ("destination_path", models.CharField(db_index=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("quarantined", "Quarantined"),
                        ],
                        db_index=True,
                        default="detected",
                        max_length=30,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "process_name",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "destination_volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_transfers",
                        to="file_tracking.diskvolume",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_transfers",
                        to="file_tracking.diskvolume",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("moved", "Moved"),
                            ("copied", "Copied"),
                            ("deleted", "Deleted"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "source_path",
                    models.CharField(blank=True, db_index=True, max_length=1000),
                ),
                (
                    "destination_path",
                    models.CharField(blank=True, db_index=True, max_length=1000),
                ),
                ("payload", models.JSONField(default=dict)),
                ("observed_at", models.DateTimeField(db_index=True)),
                (
                    "transfer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="file_tracking.filetransfer",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
            },
        ),
        migrations.CreateModel(
            name="FileAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_file_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="file_tracking.filetransfer",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="file_tracking.trackingrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="filetransfer",
            index=models.Index(
                fields=["status", "created_at"], name="file_tracki_status_cac0fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filetransfer",
            index=models.Index(
                fields=["source_volume", "destination_volume"],
                name="file_tracki_source__5ed2a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="filetransfer",
            index=models.Index(
                fields=["file_extension", "size_bytes"],
                name="file_tracki_file_ex_e3cc06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileevent",
            index=models.Index(
                fields=["event_type", "observed_at"],
                name="file_tracki_event_t_d4b0a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="filealert",
            index=models.Index(
                fields=["severity", "status", "created_at"],
                name="file_tracki_severit_a54f3a_idx",
            ),
        ),
    ]
