# Generated by Django 4.2.13 on 2026-06-04 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_tracking", "0002_seed_tracking_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesktopDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "device_id",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("name", models.CharField(db_index=True, max_length=160)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("laptop", "Laptop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("server", "Server"),
                            ("nas", "NAS"),
                            ("storage", "Storage"),
                        ],
                        db_index=True,
                        default="desktop",
                        max_length=30,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                (
                    "mac_address",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("os_name", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Maintenance"),
                        ],
                        db_index=True,
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("storage_path", models.CharField(max_length=1000)),
                ("total_storage_bytes", models.BigIntegerField(default=0)),
                ("used_storage_bytes", models.BigIntegerField(default=0)),
                ("cpu_percent", models.FloatField(default=0)),
                ("ram_percent", models.FloatField(default=0)),
                ("disk_percent", models.FloatField(default=0)),
                ("transfer_status", models.CharField(blank=True, max_length=120)),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="desktop_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("original_name", models.CharField(db_index=True, max_length=255)),
                ("stored_name", models.CharField(max_length=255)),
                ("relative_path", models.CharField(blank=True, max_length=1000)),
                ("storage_path", models.CharField(max_length=1000)),
                ("content_type", models.CharField(blank=True, max_length=160)),
                (
                    "extension",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("size_bytes", models.BigIntegerField(db_index=True, default=0)),
                (
                    "checksum",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("deploying", "Deploying"),
                            ("deployed", "Deployed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("deployed_path", models.CharField(blank=True, max_length=1000)),
                (
                    "security_scan_status",
                    models.CharField(db_index=True, default="clean", max_length=80),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_project_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_project_files",
                        to="file_tracking.desktopdevice",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_project_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_project_files",
                        to="file_tracking.desktopdevice",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_project_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhysicalStorageFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("path", models.CharField(max_length=1000, unique=True)),
                (
                    "extension",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("size_bytes", models.BigIntegerField(db_index=True, default=0)),
                (
                    "checksum",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physical_storage_files",
                        to="file_tracking.desktopdevice",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physical_storage_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("connecting", "Connecting"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="disconnected",
                        max_length=30,
                    ),
                ),
                (
                    "transport",
                    models.CharField(db_index=True, default="websocket", max_length=80),
                ),
                ("encryption", models.CharField(default="TLS 1.3", max_length=80)),
                (
                    "connected_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="file_tracking.desktopdevice",
                    ),
                ),
                (
                    "source_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="file_tracking.desktopdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DesktopTransferJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("file_name", models.CharField(db_index=True, max_length=255)),
                ("source_path", models.CharField(max_length=1000)),
                ("destination_path", models.CharField(max_length=1000)),
                ("size_bytes", models.BigIntegerField(db_index=True, default=0)),
                ("bytes_transferred", models.BigIntegerField(default=0)),
                ("progress_percent", models.FloatField(default=0)),
                ("speed_bytes_per_sec", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("transfer_mode", models.CharField(default="chunked", max_length=80)),
                ("encryption", models.CharField(default="TLS 1.3", max_length=80)),
                (
                    "checksum",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="desktop_transfer_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="desktop_transfer_destinations",
                        to="file_tracking.desktopdevice",
                    ),
                ),
                (
                    "project_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_jobs",
                        to="file_tracking.projectfile",
                    ),
                ),
                (
                    "source_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="desktop_transfer_sources",
                        to="file_tracking.desktopdevice",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="desktop_transfer_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesktopTransferAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("action", models.CharField(db_index=True, max_length=80)),
                ("message", models.CharField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="desktop_transfer_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="file_tracking.desktopdevice",
                    ),
                ),
                (
                    "project_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="file_tracking.projectfile",
                    ),
                ),
                (
                    "transfer_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="file_tracking.desktoptransferjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChunkUploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "upload_id",
                    models.CharField(db_index=True, max_length=120, unique=True),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("relative_path", models.CharField(blank=True, max_length=1000)),
                ("total_size", models.BigIntegerField(default=0)),
                ("total_chunks", models.PositiveIntegerField(default=1)),
                ("received_chunks", models.JSONField(blank=True, default=list)),
                ("temp_dir", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "destination_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_upload_sessions",
                        to="file_tracking.desktopdevice",
                    ),
                ),
                (
                    "project_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_sessions",
                        to="file_tracking.projectfile",
                    ),
                ),
                (
                    "source_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_sessions",
                        to="file_tracking.desktopdevice",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunk_upload_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(
                fields=["status", "created_at"], name="file_tracki_status_2c6f7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(
                fields=["uploaded_by", "status"], name="file_tracki_uploade_d1b7cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(
                fields=["destination_device", "status"],
                name="file_tracki_destina_b4fe8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="physicalstoragefile",
            index=models.Index(
                fields=["device", "extension"], name="file_tracki_device__c09f02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceconnection",
            index=models.Index(
                fields=["source_device", "destination_device", "status"],
                name="file_tracki_source__be9e04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deviceconnection",
            index=models.Index(
                fields=["status", "updated_at"], name="file_tracki_status_d991d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="desktoptransferjob",
            index=models.Index(
                fields=["status", "created_at"], name="file_tracki_status_18fa0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="desktoptransferjob",
            index=models.Index(
                fields=["source_device", "destination_device"],
                name="file_tracki_source__9703cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="desktoptransferjob",
            index=models.Index(
                fields=["uploaded_by", "status"], name="file_tracki_uploade_213256_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="desktoptransferauditlog",
            index=models.Index(
                fields=["action", "created_at"], name="file_tracki_action_2ec978_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="desktopdevice",
            index=models.Index(
                fields=["status", "device_type"], name="file_tracki_status_2e9b70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="desktopdevice",
            index=models.Index(
                fields=["owner", "status"], name="file_tracki_owner_i_62a6ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chunkuploadsession",
            index=models.Index(
                fields=["uploaded_by", "status"], name="file_tracki_uploade_97c059_idx"
            ),
        ),
    ]
