# Generated by Django 4.2.13 on 2026-05-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_keys", "0003_apikey_key_hash_role_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
