# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_keys", "0004_alter_apikey_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="allowed_scopes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="apikey",
            name="environment",
            field=models.CharField(
                choices=[("local", "Local"), ("staging", "Staging"), ("production", "Production")],
                db_index=True,
                default="production",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="key_type",
            field=models.CharField(
                choices=[
                    ("chatbot", "Chatbot"),
                    ("crm", "CRM"),
                    ("erp", "ERP"),
                    ("webhook", "Webhook"),
                    ("ai_agent", "AI Agent"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                default="custom",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["project", "key_type", "environment"], name="api_keys_ap_project_910f6d_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["is_active", "expires_at"], name="api_keys_ap_is_acti_51dd6d_idx"),
        ),
    ]
