# Generated by Django 4.2.17 on 2026-06-09 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_keys", "0005_apikey_enterprise_integration_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apikey",
            new_name="api_keys_ap_project_25747e_idx",
            old_name="api_keys_ap_project_910f6d_idx",
        ),
        migrations.RenameIndex(
            model_name="apikey",
            new_name="api_keys_ap_is_acti_f2ab49_idx",
            old_name="api_keys_ap_is_acti_51dd6d_idx",
        ),
    ]
