# Generated by Django 4.2.13 on 2026-05-22 02:55

import apps.ai.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0007_uceproject_ucemilestone_ucetask_ucetimeentry_and_more"),
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(default="AI Command Session", max_length=180),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("HOSTING", "Hosting Manager"),
                            ("DEVOPS", "DevOps"),
                            ("PROJECT", "Project Assistant"),
                            ("SUPPORT", "Support"),
                            ("FILES", "File Analyzer"),
                            ("AUTOMATION", "Automation"),
                        ],
                        default="GENERAL",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("model_provider", models.CharField(default="local", max_length=40)),
                (
                    "model_name",
                    models.CharField(
                        default="manageai-enterprise-local", max_length=80
                    ),
                ),
                ("memory", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_sessions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("ASSISTANT", "Assistant"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.assistantsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.ai.models.assistant_attachment_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=160)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("analysis", models.JSONField(blank=True, default=dict)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="ai.assistantmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="assistantsession",
            index=models.Index(
                fields=["owner", "status", "-updated_at"],
                name="ai_assistan_owner_i_7b18f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assistantmessage",
            index=models.Index(
                fields=["session", "created_at"], name="ai_assistan_session_c7d46c_idx"
            ),
        ),
    ]
