# Generated by Django 4.2.17 on 2026-06-09 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0008_project_hosting_lifecycle_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("machine_id", models.CharField(db_index=True, max_length=160)),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("os_name", models.CharField(blank=True, max_length=120)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("localhost", "Localhost"),
                            ("development", "Development"),
                            ("qa", "QA"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        db_index=True,
                        default="development",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("degraded", "Degraded"),
                            ("offline", "Offline"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="offline",
                        max_length=24,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=40)),
                (
                    "token_prefix",
                    models.CharField(db_index=True, max_length=16, unique=True),
                ),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("capabilities", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ManagedProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(db_index=True, max_length=180)),
                ("name", models.CharField(max_length=220)),
                ("developer_name", models.CharField(blank=True, max_length=180)),
                ("machine_name", models.CharField(blank=True, max_length=255)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("localhost", "Localhost"),
                            ("development", "Development"),
                            ("qa", "QA"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        db_index=True,
                        default="development",
                        max_length=24,
                    ),
                ),
                (
                    "framework",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("language", models.CharField(blank=True, max_length=80)),
                (
                    "root_path_hash",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("repository_url", models.URLField(blank=True)),
                (
                    "runtime_status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("degraded", "Degraded"),
                            ("error", "Error"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=24,
                    ),
                ),
                ("current_branch", models.CharField(blank=True, max_length=160)),
                ("last_commit_sha", models.CharField(blank=True, max_length=80)),
                ("last_commit_message", models.CharField(blank=True, max_length=500)),
                ("last_commit_author", models.CharField(blank=True, max_length=180)),
                ("last_commit_at", models.DateTimeField(blank=True, null=True)),
                (
                    "build_status",
                    models.CharField(
                        choices=[
                            ("passing", "Passing"),
                            ("failing", "Failing"),
                            ("building", "Building"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=24,
                    ),
                ),
                (
                    "deployment_status",
                    models.CharField(
                        choices=[
                            ("not_deployed", "Not deployed"),
                            ("ready", "Ready"),
                            ("deployed", "Deployed"),
                            ("failed", "Failed"),
                            ("rollback_ready", "Rollback ready"),
                        ],
                        db_index=True,
                        default="not_deployed",
                        max_length=32,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=80)),
                (
                    "port",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("url", models.URLField(blank=True)),
                ("health_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="project_intelligence.machineagent",
                    ),
                ),
                (
                    "linked_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intelligence_nodes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["environment", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeploymentSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("build", "Build"),
                            ("deployment", "Deployment"),
                            ("rollback", "Rollback"),
                            ("readiness", "Readiness"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("risky", "Risky"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=80)),
                (
                    "release_id",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                ("commit_sha", models.CharField(blank=True, max_length=80)),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployment_signals",
                        to="project_intelligence.machineagent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_signals",
                        to="project_intelligence.managedproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("restart", "Restart"),
                            ("build", "Build"),
                            ("deploy", "Deploy"),
                            ("rollback", "Rollback"),
                            ("collect_logs", "Collect logs"),
                            ("refresh_discovery", "Refresh discovery"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("acknowledged", "Acknowledged"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="project_intelligence.machineagent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commands",
                        to="project_intelligence.managedproject",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_agent_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cpu_percent", models.FloatField(default=0)),
                ("memory_percent", models.FloatField(default=0)),
                ("memory_mb", models.FloatField(default=0)),
                ("disk_percent", models.FloatField(default=0)),
                ("network_rx_bps", models.BigIntegerField(default=0)),
                ("network_tx_bps", models.BigIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("requests_per_second", models.FloatField(default=0)),
                ("error_rate_percent", models.FloatField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("process_count", models.PositiveIntegerField(default=0)),
                ("container_count", models.PositiveIntegerField(default=0)),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metrics",
                        to="project_intelligence.machineagent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="project_intelligence.managedproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-recorded_at"],
                        name="project_int_project_1efbb6_idx",
                    ),
                    models.Index(
                        fields=["agent", "-recorded_at"],
                        name="project_int_agent_i_4b2107_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=140)),
                (
                    "integration",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                        db_index=True,
                        default="incoming",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("retried", "Retried"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                    ),
                ),
                ("processing_time_ms", models.PositiveIntegerField(default=0)),
                (
                    "response_code",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                ("request_body", models.JSONField(blank=True, default=dict)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("retry_history", models.JSONField(blank=True, default=list)),
                ("execution_trace", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("signature_valid", models.BooleanField(db_index=True, default=True)),
                ("threat_score", models.PositiveSmallIntegerField(default=0)),
                ("ai_analysis", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="project_intelligence.machineagent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="project_intelligence.managedproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-occurred_at"],
                        name="project_int_status_7a9957_idx",
                    ),
                    models.Index(
                        fields=["integration", "event_type", "-occurred_at"],
                        name="project_int_integra_7d16a9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(blank=True, db_index=True, max_length=120)),
                ("message", models.TextField()),
                (
                    "trace_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="project_intelligence.machineagent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="project_intelligence.managedproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["project", "level", "-timestamp"],
                        name="project_int_project_bb5c04_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="managedproject",
            index=models.Index(
                fields=["environment", "runtime_status"],
                name="project_int_environ_76ddf7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="managedproject",
            index=models.Index(
                fields=["framework", "build_status"],
                name="project_int_framewo_8d0164_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="managedproject",
            index=models.Index(
                fields=["deployment_status", "updated_at"],
                name="project_int_deploym_eb89e5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedproject",
            constraint=models.UniqueConstraint(
                fields=("agent", "external_id", "environment"),
                name="unique_agent_project_environment",
            ),
        ),
        migrations.AddIndex(
            model_name="machineagent",
            index=models.Index(
                fields=["environment", "status"], name="project_int_environ_cce2bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machineagent",
            index=models.Index(
                fields=["machine_id", "environment"],
                name="project_int_machine_5107fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentcommand",
            index=models.Index(
                fields=["agent", "status", "created_at"],
                name="project_int_agent_i_7d4521_idx",
            ),
        ),
    ]
