# Generated by Django 4.2.16 on 2026-05-12 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("ip_address", models.GenericIPAddressField()),
                ("ssh_port", models.PositiveIntegerField(default=22)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("down", "Down"),
                            ("maintenance", "Maintenance"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=24,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServerMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_percent", models.FloatField(default=0)),
                ("memory_percent", models.FloatField(default=0)),
                ("disk_percent", models.FloatField(default=0)),
                ("uptime_seconds", models.BigIntegerField(default=0)),
                ("network_bytes_sent", models.BigIntegerField(default=0)),
                ("network_bytes_recv", models.BigIntegerField(default=0)),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="server_monitor.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["server", "-recorded_at"],
                        name="server_moni_server__dcce4d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiskMount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mount_point", models.CharField(max_length=255)),
                ("total_gb", models.FloatField(default=0)),
                ("used_gb", models.FloatField(default=0)),
                ("free_gb", models.FloatField(default=0)),
                ("usage_percent", models.FloatField(default=0)),
                ("alert_threshold", models.FloatField(default=90)),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disk_mounts",
                        to="server_monitor.server",
                    ),
                ),
            ],
            options={
                "ordering": ["server", "mount_point"],
                "indexes": [
                    models.Index(
                        fields=["server", "mount_point", "-recorded_at"],
                        name="server_moni_server__41ad76_idx",
                    )
                ],
            },
        ),
    ]
