# Generated by Django 5.2.14 on 2026-05-11 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("source_module", models.CharField(db_index=True, max_length=50)),
                ("target_module", models.CharField(db_index=True, max_length=50)),
                ("entity_id", models.CharField(db_index=True, max_length=100)),
                (
                    "conflict_detected",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "resolution_strategy",
                    models.CharField(
                        choices=[
                            ("timestamp", "Last-Write-Wins"),
                            ("priority", "Module-Priority"),
                            ("manual", "Manual Review"),
                        ],
                        default="timestamp",
                        max_length=20,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_module", "target_module", "entity_id"],
                        name="webhooks_da_source__7b8f5f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("source_module", models.CharField(db_index=True, max_length=50)),
                (
                    "entity_type",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "entity_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_module", "event_type", "created_at"],
                        name="webhooks_ev_source__1a565e_idx",
                    )
                ],
            },
        ),
    ]
