# Generated by Django 4.2.16 on 2026-05-08 08:41

import uuid

from django.db import migrations, models


def populate_secret_ids(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(secret_id__isnull=True):
        prefix = "DEV" if user.role == "DEVELOPER" else "USR"
        while True:
            value = f"{prefix}-{uuid.uuid4().hex[:8].upper()}"
            if not User.objects.filter(secret_id=value).exists():
                user.secret_id = value
                user.save(update_fields=["secret_id"])
                break


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="availability_status",
            field=models.CharField(blank=True, default="Available", max_length=80),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role_title",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="user",
            name="secret_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_secret_ids, migrations.RunPython.noop),
    ]
