# Generated by Django 4.2.16 on 2026-05-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("enterprise", "__first__"),
        ("accounts", "0003_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="enterprise.company",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="enterprise.company",
            ),
        ),
    ]
