# Generated by Django 4.2.16 on 2026-05-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_team_company_user_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="face_enrolled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="face_hash",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="user",
            name="face_image",
            field=models.ImageField(blank=True, null=True, upload_to="face_profiles/"),
        ),
        migrations.AddField(
            model_name="user",
            name="face_login_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
