# Generated by Codex on 2026-05-11

from django.db import migrations, models
import django.db.models.deletion


def backfill_approval_status(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(approval_status="").update(approval_status="APPROVED")
    User.objects.filter(is_active=True, approval_status="PENDING").update(approval_status="APPROVED")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_face_embeddings_user_face_security_checks"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("SUSPENDED", "Suspended"),
                ],
                db_index=True,
                default="APPROVED",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_users",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_approval_status, migrations.RunPython.noop),
    ]
