# Generated by Django 4.2.16 on 2026-05-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="day_progress",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="task",
            name="workflow_day",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
