# Generated by Django 4.2.16 on 2026-05-08 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0002_task_day_progress_task_workflow_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("NOT_SUBMITTED", "Not submitted"),
                    ("PENDING", "Pending approval"),
                    ("APPROVED", "Approved"),
                    ("DISAPPROVED", "Disapproved"),
                ],
                default="NOT_SUBMITTED",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="completion_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="delay_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="depends_on",
            field=models.ManyToManyField(
                blank=True, related_name="unlocks", to="tasks.task"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="review_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="workflow_loop_key",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
