# Generated by Django 4.2.16 on 2026-05-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_approval_status_task_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
