# Generated by Django 4.2.16 on 2026-05-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deploymentcontrol",
            name="commit_sha",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="deploymentcontrol",
            name="source_branch",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="deploymenthistory",
            name="commit_sha",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="deploymenthistory",
            name="source_branch",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
