# Generated by Django 4.2.13 on 2026-06-05 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0003_deploymentrecord"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="deploymentrecord",
            new_name="deployments_project_6bfc48_idx",
            old_name="deployment_project_65fa3a_idx",
        ),
        migrations.RenameIndex(
            model_name="deploymentrecord",
            new_name="deployments_hosting_d86e47_idx",
            old_name="deployment_hosting_2f9f33_idx",
        ),
    ]
