# Generated by Django 4.2.16 on 2026-05-09 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_team"),
        ("projects", "0004_project_approval_note_project_approval_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("domain", models.CharField(blank=True, max_length=180)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServerControlState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "health",
                    models.CharField(
                        choices=[
                            ("STABLE", "Stable"),
                            ("SCALING", "Scaling"),
                            ("OVERLOADED", "Overloaded"),
                            ("OFFLINE", "Offline"),
                        ],
                        default="STABLE",
                        max_length=32,
                    ),
                ),
                ("scale_units", models.PositiveSmallIntegerField(default=1)),
                (
                    "storage_total_gb",
                    models.DecimalField(decimal_places=2, default=500, max_digits=10),
                ),
                (
                    "storage_used_gb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("file_count", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("incoming_requests", models.PositiveIntegerField(default=0)),
                ("outgoing_requests", models.PositiveIntegerField(default=0)),
                ("uptime_seconds", models.PositiveBigIntegerField(default=0)),
                (
                    "last_checked_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "company",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_control",
                        to="enterprise.company",
                    ),
                ),
            ],
            options={
                "ordering": ["company__name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("scope", models.TextField()),
                ("features", models.JSONField(blank=True, default=list)),
                ("timeline_days", models.PositiveIntegerField(default=30)),
                (
                    "development_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "hosting_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "maintenance_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_estimates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimates",
                        to="enterprise.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_estimates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimates",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="HostingConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("AWS", "AWS"),
                            ("AZURE", "Azure"),
                            ("GCP", "Google Cloud"),
                            ("DIGITALOCEAN", "DigitalOcean"),
                            ("VERCEL", "Vercel"),
                            ("NETLIFY", "Netlify"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("endpoint_url", models.URLField(blank=True)),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "Connected"),
                            ("DEGRADED", "Degraded"),
                            ("DISCONNECTED", "Disconnected"),
                        ],
                        default="DISCONNECTED",
                        max_length=32,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=80)),
                ("last_deployed_at", models.DateTimeField(blank=True, null=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosting_connections",
                        to="enterprise.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosting_connections",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=220)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_events",
                        to="enterprise.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPENAI", "OpenAI"),
                            ("META", "Meta"),
                            ("OPEN_SOURCE", "Open source"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=32,
                    ),
                ),
                ("key_hash", models.CharField(max_length=128)),
                ("key_preview", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="enterprise.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "name"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=80)),
                ("label", models.CharField(max_length=160)),
                (
                    "dashboard",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("SUPER_ADMIN", "Super Admin"),
                            ("ADMIN", "Admin"),
                            ("DEVELOPER", "Developer"),
                            ("CLIENT", "Client"),
                        ],
                        default="GLOBAL",
                        max_length=32,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="enterprise.company",
                    ),
                ),
            ],
            options={
                "ordering": ["dashboard", "label"],
                "unique_together": {("company", "key", "dashboard")},
            },
        ),
        migrations.CreateModel(
            name="CompanyService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "recurring_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="enterprise.company",
                    ),
                ),
            ],
            options={
                "ordering": ["company__name", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="APIKeyGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("can_view", models.BooleanField(default=True)),
                ("can_use", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="enterprise.apikey",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_key_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_api_key_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["api_key__name", "developer__email"],
                "unique_together": {("api_key", "developer")},
            },
        ),
    ]
