# Generated by Django 4.2.16 on 2026-05-09 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_connection_engine(apps, schema_editor):
    Company = apps.get_model("enterprise", "Company")
    UniversalConnector = apps.get_model("enterprise", "UniversalConnector")
    NetworkTelemetry = apps.get_model("enterprise", "NetworkTelemetry")
    VoiceCommandIntent = apps.get_model("enterprise", "VoiceCommandIntent")

    company, _ = Company.objects.get_or_create(
        slug="primary-company",
        defaults={"name": "Primary Company", "description": "Default isolated company workspace."},
    )
    defaults = [
        ("CRM Hub", "CRM", "Internal CRM"),
        ("ERP Ledger", "ERP", "Company ERP"),
        ("HR People Sync", "HR", "HRMS"),
        ("Inventory Control", "INVENTORY", "Warehouse"),
        ("Project Workspace", "PROJECT_MANAGEMENT", "ManageAI"),
        ("Hosting Fabric", "HOSTING", "Multi-cloud"),
        ("Production Server", "SERVER", "Platform agent"),
        ("API Gateway", "API", "Internal Gateway"),
    ]
    for name, category, vendor in defaults:
        UniversalConnector.objects.get_or_create(
            company=company,
            name=name,
            category=category,
            defaults={"vendor": vendor, "status": "CONNECTED", "is_enabled": True, "latency_ms": 64},
        )
    NetworkTelemetry.objects.get_or_create(
        company=company,
        source="platform-agent",
        defaults={"upload_mbps": 72, "download_mbps": 260, "latency_ms": 24, "packet_loss_percent": 0, "requests_per_second": 96, "health_score": 98},
    )
    intents = [
        ("show server health", "OPEN_MONITORING", "monitoring", "ADMIN"),
        ("sync crm", "SYNC_CONNECTOR", "connections", "ADMIN"),
        ("open my tasks", "OPEN_TASKS", "tasks", "DEVELOPER"),
        ("create client ticket", "OPEN_TICKETS", "tickets", "CLIENT"),
    ]
    for phrase, action, target_module, minimum_role in intents:
        VoiceCommandIntent.objects.get_or_create(
            company=company,
            phrase=phrase,
            target_module=target_module,
            defaults={"action": action, "minimum_role": minimum_role, "status": "ACTIVE"},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("enterprise", "0002_seed_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversalConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CRM", "CRM"),
                            ("ERP", "ERP"),
                            ("HR", "HR"),
                            ("INVENTORY", "Inventory"),
                            ("PROJECT_MANAGEMENT", "Project Management"),
                            ("HOSTING", "Hosting"),
                            ("SERVER", "Server"),
                            ("API", "API"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=40,
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=120)),
                ("endpoint_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "Connected"),
                            ("SYNCING", "Syncing"),
                            ("DEGRADED", "Degraded"),
                            ("DISCONNECTED", "Disconnected"),
                        ],
                        default="DISCONNECTED",
                        max_length=32,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("sync_interval_seconds", models.PositiveIntegerField(default=300)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("records_in", models.PositiveIntegerField(default=0)),
                ("records_out", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("ai_enhancement_enabled", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connectors",
                        to="enterprise.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connectors",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
                "unique_together": {("company", "name", "category")},
            },
        ),
        migrations.CreateModel(
            name="NetworkTelemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "upload_mbps",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "download_mbps",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "packet_loss_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "requests_per_second",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("health_score", models.PositiveSmallIntegerField(default=100)),
                ("source", models.CharField(default="platform-agent", max_length=80)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_telemetry",
                        to="enterprise.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("SYNC_STARTED", "Sync started"),
                            ("SYNC_COMPLETED", "Sync completed"),
                            ("SYNC_FAILED", "Sync failed"),
                            ("CONTROL", "Control"),
                            ("DEPLOYMENT", "Deployment"),
                            ("USER_ACTION", "User action"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connection_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_events",
                        to="enterprise.company",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="enterprise.universalconnector",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connection_events",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceCommandIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phrase", models.CharField(max_length=180)),
                ("action", models.CharField(max_length=120)),
                ("target_module", models.CharField(max_length=80)),
                ("minimum_role", models.CharField(default="ADMIN", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("DISABLED", "Disabled")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_intents",
                        to="enterprise.company",
                    ),
                ),
            ],
            options={
                "ordering": ["target_module", "phrase"],
                "unique_together": {("company", "phrase", "target_module")},
            },
        ),
        migrations.RunPython(seed_connection_engine, migrations.RunPython.noop),
    ]
