# Generated by Django 4.2.16 on 2026-05-09 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "enterprise",
            "0003_universalconnector_networktelemetry_connectionevent_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("is_team_bot_enabled", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_channels",
                        to="enterprise.company",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collaboration_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_channels",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "project", "name")},
            },
        ),
        migrations.CreateModel(
            name="CollaborationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "Message"),
                            ("FILE", "File"),
                            ("CONFIG", "Config"),
                            ("BOT", "Bot"),
                        ],
                        default="MESSAGE",
                        max_length=16,
                    ),
                ),
                ("ciphertext", models.TextField()),
                ("nonce", models.CharField(blank=True, max_length=120)),
                ("sender_public_key", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(blank=True, upload_to="collaboration/%Y/%m/"),
                ),
                ("attachment_name", models.CharField(blank=True, max_length=220)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="enterprise.collaborationchannel",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collaboration_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
