# Generated by Django 4.2.16 on 2026-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enterprise", "0004_collaborationchannel_collaborationmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectestimate",
            name="demo_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="demo_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="ui_preview",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
