# Generated by Django 4.2.16 on 2026-05-09 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("enterprise", "0006_seed_face_login_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerFileAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_path", models.CharField(max_length=500)),
                ("file_name", models.CharField(blank=True, max_length=220)),
                ("file_size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("BROWSE", "Browse"),
                            ("VIEW", "View"),
                            ("DOWNLOAD", "Download"),
                            ("UPLOAD", "Upload"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "accessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_accesses",
                        to="enterprise.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CloudStorageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("AWS_S3", "AWS S3"),
                            ("AZURE_BLOB", "Azure Blob Storage"),
                            ("GCP_STORAGE", "Google Cloud Storage"),
                            ("LOCAL", "Local Storage"),
                        ],
                        default="LOCAL",
                        max_length=32,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("endpoint_url", models.URLField(blank=True)),
                ("bucket_name", models.CharField(blank=True, max_length=180)),
                ("access_key_hash", models.CharField(blank=True, max_length=128)),
                (
                    "storage_limit_gb",
                    models.DecimalField(decimal_places=2, default=100, max_digits=10),
                ),
                (
                    "current_usage_gb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("file_count", models.PositiveIntegerField(default=0)),
                ("is_backup_enabled", models.BooleanField(default=True)),
                ("last_backup_at", models.DateTimeField(blank=True, null=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_settings",
                        to="enterprise.company",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_storage_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cloud Storage Settings",
            },
        ),
        migrations.CreateModel(
            name="AuthenticationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allow_password_change", models.BooleanField(default=True)),
                ("allow_forgot_password", models.BooleanField(default=True)),
                ("allow_face_login", models.BooleanField(default=False)),
                (
                    "default_login_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("FACE", "Face Recognition"),
                            ("BOTH", "Both"),
                        ],
                        default="EMAIL",
                        max_length=32,
                    ),
                ),
                (
                    "password_expiry_days",
                    models.PositiveSmallIntegerField(
                        default=90, help_text="0 means no expiry"
                    ),
                ),
                ("min_password_length", models.PositiveSmallIntegerField(default=8)),
                ("require_2fa", models.BooleanField(default=False)),
                (
                    "session_timeout_minutes",
                    models.PositiveSmallIntegerField(default=60),
                ),
                (
                    "admin_login_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Login methods allowed for admins",
                    ),
                ),
                ("developer_login_methods", models.JSONField(blank=True, default=list)),
                ("client_login_methods", models.JSONField(blank=True, default=list)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_settings",
                        to="enterprise.company",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_auth_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Authentication Settings",
            },
        ),
        migrations.CreateModel(
            name="UserAccessControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("TASKS", "Tasks"),
                            ("COLLABORATION", "Collaboration"),
                            ("TICKETS", "Tickets"),
                            ("NOTIFICATIONS", "Notifications"),
                            ("AI_CHATBOT", "AI Chatbot"),
                            ("MONITORING", "Monitoring"),
                            ("CONNECTION_ENGINE", "Connection Engine"),
                            ("PROJECT_FILES", "Project Files"),
                            ("ANALYTICS", "Analytics"),
                            ("AUDIT", "Audit Logs"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("ADMIN", "Admin"),
                            ("DEVELOPER", "Developer"),
                            ("CLIENT", "Client"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        blank=True, default=list, help_text="List of allowed actions"
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_controls",
                        to="enterprise.company",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_access_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__email", "module"],
                "unique_together": {("user", "module")},
            },
        ),
        migrations.CreateModel(
            name="SystemSettingsAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("MODULE_CONTROL", "Module Control"),
                            ("ACCESS_CONTROL", "Access Control"),
                            ("AUTH_SETTINGS", "Auth Settings"),
                            ("STORAGE_SETTINGS", "Storage Settings"),
                            ("API_KEY", "API Key"),
                            ("FEATURE_FLAG", "Feature Flag"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                            ("ENABLE", "Enabled"),
                            ("DISABLE", "Disabled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("change_summary", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings_audit_logs",
                        to="enterprise.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "-created_at"],
                        name="enterprise__company_317924_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemModuleControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("TASKS", "Tasks"),
                            ("COLLABORATION", "Collaboration"),
                            ("TICKETS", "Tickets"),
                            ("NOTIFICATIONS", "Notifications"),
                            ("AI_CHATBOT", "AI Chatbot"),
                            ("MONITORING", "Monitoring"),
                            ("CONNECTION_ENGINE", "Connection Engine"),
                            ("PROJECT_FILES", "Project Files"),
                            ("ANALYTICS", "Analytics"),
                            ("AUDIT", "Audit Logs"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="module_control_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_controls",
                        to="enterprise.company",
                    ),
                ),
            ],
            options={
                "ordering": ["module"],
                "unique_together": {("company", "module")},
            },
        ),
    ]
