# Generated by Django 5.0.8 on 2026-05-08 06:13

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.documents.models.document_upload_path
                    ),
                ),
                ("category", models.CharField(default="General", max_length=80)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Internal"),
                            ("CLIENT", "Client"),
                            ("PUBLIC", "Public"),
                        ],
                        default="INTERNAL",
                        max_length=32,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=30)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("extension", models.CharField(blank=True, max_length=20)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "visibility"],
                        name="documents_d_project_9fa4ef_idx",
                    )
                ],
            },
        ),
    ]
