# Generated by Django 4.2.16 on 2026-05-08 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="review_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending review"),
                    ("APPROVED", "Approved"),
                    ("CORRECTION_REQUESTED", "Correction requested"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
