# Generated by Django 5.2.14 on 2026-05-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("projects", "0007_uceproject_ucemilestone_ucetask_ucetimeentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="linked_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="projects.uceproject",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="crm.deal",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["company", "lifecycle_stage"],
                name="crm_contact_company_4607ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["stage", "expected_close"], name="crm_deal_stage_81b40d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["type", "activity_date"], name="crm_activit_type_3cedb7_idx"
            ),
        ),
    ]
