# Generated by Django 5.2.14 on 2026-05-11 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConnectorDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("module_id", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=120)),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("rest_api", "REST API"),
                            ("webhook", "Webhook"),
                            ("database", "Database"),
                        ],
                        max_length=30,
                    ),
                ),
                ("base_url", models.URLField(blank=True)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("bearer", "Bearer"),
                            ("api_key", "API Key"),
                            ("basic", "Basic"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                ("encrypted_credentials", models.TextField(blank=True)),
                ("field_mappings", models.JSONField(default=dict)),
                ("sync_frequency", models.PositiveIntegerField(default=300)),
                (
                    "health_status",
                    models.CharField(db_index=True, default="unknown", max_length=30),
                ),
            ],
            options={
                "ordering": ["module_id"],
                "indexes": [
                    models.Index(
                        fields=["module_id", "connection_type"],
                        name="modules_con_module__4a941b_idx",
                    )
                ],
            },
        ),
    ]
