# Generated by Django 4.2.16 on 2026-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="assignment_reason",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="ticket",
            name="auto_assigned",
            field=models.BooleanField(default=False),
        ),
    ]
