# Generated by Django 4.2.16 on 2026-05-09 18:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_ticket_identity(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")
    TicketSequence = apps.get_model("tickets", "TicketSequence")
    for ticket in Ticket.objects.select_related("project").order_by("id"):
        prefix = "INC"
        year = ticket.created_at.year if ticket.created_at else 2026
        sequence, _ = TicketSequence.objects.get_or_create(prefix=prefix, year=year)
        sequence.next_number += 1
        sequence.save(update_fields=["next_number", "updated_at"])
        priority = {
            "CRITICAL": "P1",
            "HIGH": "P2",
            "MEDIUM": "P3",
            "LOW": "P4",
        }.get(ticket.priority, ticket.priority or "P3")
        Ticket.objects.filter(pk=ticket.pk).update(
            ticket_id=f"{prefix}-{year}-{sequence.next_number:05d}",
            requester_id=ticket.raised_by_id,
            organization_id=getattr(ticket.project, "company_id", None),
            priority=priority,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("enterprise", "0007_serverfileaccess_cloudstoragesettings_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "accounts",
            "0005_user_face_enrolled_at_user_face_hash_user_face_image_and_more",
        ),
        ("tickets", "0003_ticketattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("current_stage_order", models.PositiveSmallIntegerField(default=1)),
                ("comments", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("name", models.CharField(max_length=160)),
                ("approver_role", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["approval_request", "order"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("stages", models.JSONField(blank=True, default=list)),
                (
                    "approver_type",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("ROLE", "Role"),
                            ("MANAGER", "Manager"),
                        ],
                        default="USER",
                        max_length=16,
                    ),
                ),
                ("is_parallel", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(help_text="0=Monday, 6=Sunday"),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("timezone", models.CharField(default="UTC", max_length=80)),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("date", models.DateField()),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P1", "P1 Critical"),
                            ("P2", "P2 High"),
                            ("P3", "P3 Medium"),
                            ("P4", "P4 Low"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "first_response_time",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                (
                    "resolution_time",
                    models.DurationField(default=datetime.timedelta(seconds=28800)),
                ),
                ("business_hours_only", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="TicketActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("field_changed", models.CharField(blank=True, max_length=80)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TicketSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prefix", models.CharField(max_length=8)),
                ("year", models.PositiveSmallIntegerField()),
                ("next_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("logs", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("TICKET_CREATED", "Ticket Created"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("SLA_BREACHED", "SLA Breached"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=32,
                    ),
                ),
                ("trigger_conditions", models.JSONField(blank=True, default=dict)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="assigned_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tickets",
                to="accounts.team",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="category",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="ticket",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ticket",
            name="first_response_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="impact",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Critical")],
                default=2,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="enterprise.company",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="parent_ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_tickets",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="related_tickets",
            field=models.ManyToManyField(blank=True, to="tickets.ticket"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="severity",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Critical")],
                default=2,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sla_breached",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sla_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sla_pause_reason",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sla_paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="subcategory",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="ticket",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="ticket",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCIDENT", "Incident"),
                    ("SERVICE_REQUEST", "Service Request"),
                    ("PROBLEM", "Problem"),
                    ("CHANGE", "Change"),
                    ("TASK", "Task"),
                ],
                default="INCIDENT",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="urgency",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Critical")],
                default=2,
            ),
        ),
        migrations.AddField(
            model_name="ticketattachment",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="tickets.ticketcomment",
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="mentions",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_ticket_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("P1", "P1 Critical"),
                    ("P2", "P2 High"),
                    ("P3", "P3 Medium"),
                    ("P4", "P4 Low"),
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                default="P3",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("PENDING", "Pending"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                    ("OPEN", "Open"),
                    ("TRIAGED", "Triaged"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
        migrations.RunPython(backfill_ticket_identity, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_id",
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organization", "status", "priority"],
                name="tickets_tic_organiz_c90b8c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["requester", "status"], name="tickets_tic_request_43654c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["sla_due_at", "sla_breached"],
                name="tickets_tic_sla_due_f23b21_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["ticket_id"], name="tickets_tic_ticket__5a4a00_idx"
            ),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_templates",
                to="enterprise.company",
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="tickets.workflowtemplate",
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_executions",
                to="tickets.ticket",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticketsequence",
            unique_together={("prefix", "year")},
        ),
        migrations.AddField(
            model_name="ticketactivity",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketactivity",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sla_policies",
                to="enterprise.company",
            ),
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_items",
                to="enterprise.company",
            ),
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_service_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidays",
                to="enterprise.company",
            ),
        ),
        migrations.AddField(
            model_name="businesshours",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_hours",
                to="enterprise.company",
            ),
        ),
        migrations.AddField(
            model_name="approvaltemplate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_templates",
                to="enterprise.company",
            ),
        ),
        migrations.AddField(
            model_name="approvalstage",
            name="approval_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="tickets.approvalrequest",
            ),
        ),
        migrations.AddField(
            model_name="approvalstage",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_approval_stages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalstage",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_ticket_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_ticket_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="tickets.approvaltemplate",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="service_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="tickets.serviceitem",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["organization", "trigger_type", "is_active"],
                name="tickets_wor_organiz_dfbcb8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["status", "created_at"], name="tickets_wor_status_269332_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketactivity",
            index=models.Index(
                fields=["ticket", "-timestamp"], name="tickets_tic_ticket__350d0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketactivity",
            index=models.Index(fields=["action"], name="tickets_tic_action_e907d7_idx"),
        ),
        migrations.AddIndex(
            model_name="slapolicy",
            index=models.Index(
                fields=["organization", "priority", "is_active"],
                name="tickets_sla_organiz_619a99_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="slapolicy",
            unique_together={("organization", "name", "priority")},
        ),
        migrations.AddIndex(
            model_name="serviceitem",
            index=models.Index(
                fields=["organization", "is_active"],
                name="tickets_ser_organiz_5acfc9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceitem",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("organization", "date", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="businesshours",
            unique_together={("organization", "day_of_week", "start_time", "end_time")},
        ),
        migrations.AlterUniqueTogether(
            name="approvalstage",
            unique_together={("approval_request", "order", "name")},
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["ticket", "status"], name="tickets_app_ticket__a76e1c_idx"
            ),
        ),
    ]
