# Generated by Django 4.2.16 on 2026-05-12 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("domain", models.CharField(max_length=255, unique=True)),
                (
                    "hosting_platform",
                    models.CharField(
                        choices=[
                            ("vercel", "Vercel"),
                            ("railway", "Railway"),
                            ("aws", "AWS"),
                            ("netlify", "Netlify"),
                            ("digitalocean", "DigitalOcean"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=32,
                    ),
                ),
                ("deploy_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("live", "Live"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("link_is_active", models.BooleanField(default=True)),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("expiry_date", models.DateField(db_index=True)),
                (
                    "monthly_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_projects",
                        to="crm.company",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="HostingLifecycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("renewed", "Renewed"),
                            ("suspended", "Suspended"),
                            ("reactivated", "Reactivated"),
                            ("expired", "Expired"),
                            ("platform_changed", "Platform changed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("old_expiry", models.DateField(blank=True, null=True)),
                ("new_expiry", models.DateField(blank=True, null=True)),
                ("old_platform", models.CharField(blank=True, max_length=32)),
                ("new_platform", models.CharField(blank=True, max_length=32)),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosting_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle",
                        to="hosting.hostedproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
